[package]
name = "musiclist"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sqlite = "0.26.0"
gtk = { version = "0.4.8", package = "gtk4" }
text_io = "0.1.10"